# Generated by Django 4.2.4 on 2023-08-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrello', 'verbose_name_plural': 'Carrelli'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Elemento carrello', 'verbose_name_plural': 'Elementi carrello'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Prodotto', 'verbose_name_plural': 'Prodotti'},
        ),
    ]
