# Generated by Django 4.2.4 on 2023-08-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrello', '0002_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('generic', 'generic'), ('food', 'food'), ('drinks', 'drinks'), ('clothes', 'clothes'), ('electronics', 'electronics')], default='generic', max_length=100),
        ),
    ]
