# Generated by Django 4.2.4 on 2023-08-07 06:03

from django.db import migrations
from django.db.models.functions import Lower, Upper


def update_category(apps, schema_editor, fn):
    Product = apps.get_model('carrello', 'Product')
    db_alias = schema_editor.connection.alias
    Product.objects.using(db_alias).all().update(category=fn)


def uppercase_category(apps, schema_editor):
    update_category(apps=apps, schema_editor=schema_editor, fn=Upper('category'))


def reverse_uppercase_category(apps, schema_editor):
    update_category(apps=apps, schema_editor=schema_editor, fn=Lower('category'))


class Migration(migrations.Migration):
    dependencies = [
        ('carrello', '0003_product_category'),
    ]

    # Sovrascrive i valori di default per la categoria
    # con la versione uppercase, usando una funzione python
    operations = [
        migrations.RunPython(uppercase_category, reverse_uppercase_category)
    ]
